paths:
  images: './PostProcessingResults/images/'
  results: './PostProcessingResults/results/'
  models: ['./Models/resnet50/bs16/best_model.h5', './Models/resnet50/shuffle-lr/best_model.h5',
           './Models/inceptionresnetv2/basic/best_model.h5', './Models/vgg16/batch16/best_model.h5']

model: 
  backbones: ['resnet50', 'resnet50', 'inceptionresnetv2', 'vgg16']
  lr: 0.0001

image_size: [256, 256]

pp_parameters:
  kernel_open: 5
  kernel_close: 5
  threshold: 0.5
  replicate_pix: 3
  clip_pix: 1
  min_graph_length_pix: 10
